### ISSUE TITLE
вопрос по ci/cd . Как выкладывается сайт в прод, не пойму?)

### ISSUE THREAD

**Issue by kortov** [anmedio/junost#29]
Не могу понять, как выкладывается сайт на gh pages :) Репы с github.io у вас я не вижу, ветки gh pages в этом репозитории тоже нет. У вас какой-то приватный репо есть чтоли или я чего-то не понимаю? Мне кажется чтобы люди могли помочь вам с настройкой авт. релиза билдов, нужно как-то это дело открыть в доступ.

**Comment by NikolasMelui** [comment]
Привет!
Всё просто, в master ветке есть папка dist, там билд)) Соответственно автоматически всё подтягивается, как только мы принимаем мердж реквест, делаем билд и заливаем его в master.

**Comment by NikolasMelui** [comment]
В ближайшее время планируем сделать полноценный CI на github actions.
