### ISSUE TITLE
При открытии страницы, bundle.js грузится с localhost

### ISSUE THREAD

**Issue by kortov** [anmedio/junost#30]
https://anmedio.github.io/junost/
![image](https://user-images.githubusercontent.com/6348215/74033641-0e4a5880-49d0-11ea-8000-0e9f325ea747.png)

**Comment by NikolasMelui** [comment]
Кажется он не несет в себе никакой смысловой нагрузки.

**Comment by NikolasMelui** [comment]
Пофикшено!
