### ISSUE TITLE
Адаптивность в опасности 🔥

### ISSUE THREAD

**Issue by igorkamyshev** [anmedio/junost#8]
Привет! Крутой проект, спасибо за него. 🤗

Я нашел одну незначительную проблему. На MBP13 верстка ломается. Последний столбик не влазит.

<img width="1552" alt="Снимок экрана 2019-09-17 в 9 30 53" src="https://user-images.githubusercontent.com/26767722/65016883-078e4c80-d92e-11e9-86f7-a0299ff4b8ef.png">

<img width="1552" alt="Снимок экрана 2019-09-17 в 9 30 55" src="https://user-images.githubusercontent.com/26767722/65016881-052bf280-d92e-11e9-9baf-b52c17376be6.png">

**Comment by NikolasMelui** [comment]
Привет! Спасибо огромное за отзыв 😃
Обязательно поправим в ближайшее время.
Если будут ещё какие-то замечания или рекомендации по улучшению сервиса - welcome  ☺️👍
